# Generated by Django 3.0.2 on 2020-05-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20200529_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='price_of_product',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sku_of_product',
        ),
    ]
